---
apiVersion: v1
kind: Namespace
metadata:
  name: fb
---
apiVersion: v1
kind: pod
metadata:
  name: fb-pod
  namespace: fb
  labels:
   app: httpd
   tier: frontend-backend
   version: v1
   env: prod
spec:
  containers:
   - name: web
     image: httpd
     ports:
      - containerPort: 80
   - name: db
     image: mysql
     ports:
      - containerPort: 2310
     env:
      - name: MYSQL_ROOT_PASSWORD
	value: adminadmin
  
