---
apiVersion: v1
kind: Namespace
metadata:
  name: fb
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: fb
  labels:
   app: psql
   tier: backend
   version: master
spec:
  containers:
   - name: psql
     image: postgres
     ports:
     - containerPort: 1234
     env:
     - name: POSTGRES_PASSWORD
       value: adminadmin
     volumeMounts:
     - name : pgdata
       mountPath: /var/lib/postgresql/data
   - name: web
     image: nginx
     ports:
     - containerPort: 80
     volumeMounts:
     - name : webdata
       mountPath: /usr/share/nginx/html/
  volumes:
   - name: pgdata #volumeMount name and this name should match
     hostPath:
       path: /var/lib/postgresql
       type: DirectoryOrCreate  #always use DirectoryOrCreate for prods
   - name: webdata #volumeMount name and this name should match
     hostPath:
       path: /var/www/html
       type: DirectoryOrCreate