---
apiVersion: v1
kind: Namespace
metadata:
  name: ig
---
apiVersion: v1
kind: Pod
metadata:
  name: ig-pod
  namespace: ig
  labels:
   app: nginx
   tier: front
   version: v1
   env: prod
spec:
  containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80
  
